name: Tests

# on: [push]
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      # Install Node Js
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      # Install Node Modules
      - name: Install Node Modules
        run: npm install

      # Runs a set of commands using the runners shell
      - name: Runs Unit Tests
        run: npm run test

      # Runs a set of commands using the runners shell
      - name: Build typescript code
        run: npm run build

      # Adds automatic badges
      - name: Add Badges
        uses: rocktimsaikia/badge-it@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          badges: "gh_license, gh_version, gh_stars, gh_repo_size, gh_code_size, gh_open_issues, gh_closed_issues"
          badge-style: "flat-square"
